permissions:
  contents: read
  pages: write
  id-token: write
name: Generate pages and deploy
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
    - uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ${{ github.repository }}
        options: -v ${{ github.workspace }}/public:/output -e CONNECTIONSTRINGS__TMDB=${{ secrets.CONNECTIONSTRINGS__TMDB }}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload the output
        path: 'public'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
